import json
import os

plants_data = [
    ('sereh', 'Sereh', [
        ('Bagian tanaman sereh yang paling sering dimanfaatkan sebagai bumbu dapur dan jamu adalah...', 'Pangkal batang dan pelepah daun', 'Biji dan buah', 'Ujung akar serabut', 'A', 'Pangkal batang sereh yang tebal dan berlapis padat kaya akan minyak atsiri sitral beraroma segar.'),
        ('Aroma segar khas yang tercium dari remasan daun sereh menyerupai aroma...', 'Pandan wangi', 'Minyak sitrun atau lemon', 'Bunga mawar', 'B', 'Sereh mengandung senyawa sitral tinggi yang memberikan wangi sitrun segar alami.'),
        ('Kebutuhan sinar matahari yang paling baik untuk pertumbuhan rumpun sereh adalah...', 'Ruangan gelap tanpa cahaya', 'Tempat sangat teduh tertutup', 'Paparan sinar matahari penuh', 'C', 'Sereh tumbuh paling subur dan menghasilkan minyak atsiri optimal di bawah sinar matahari penuh.'),
        ('Cara perbanyakan tanaman sereh yang paling mudah dan umum dilakukan adalah...', 'Memisahkan anakan rumpun berakar', 'Mencangkok batang pohon', 'Menyemai spora', 'A', 'Sereh diperbanyakan dengan memisahkan tunas anakan dari rumpun induk yang sudah memiliki akar sehat.'),
        ('Salah satu manfaat seduhan air sereh hangat bagi tubuh adalah...', 'Menurunkan kadar air tubuh drastis', 'Menghangatkan badan dan meredakan kembung', 'Memicu rasa kantuk berlebih', 'B', 'Seduhan sereh secara tradisional bermanfaat menghangatkan saluran cerna dan meredakan perut kembung.'),
        ('Ciri bentuk daun tanaman sereh yang mudah diamati adalah...', 'Tumbuh melingkar tebal berair', 'Bulat lebar berbulu halus', 'Memanjang tipis menyerupai pita rumput', 'C', 'Daun sereh berbentuk pita memanjang tipis dengan tepi daun yang kesat khas keluarga rumput-rumputan.'),
        ('Kondisi media tanam yang disukai tanaman sereh agar akarnya tidak mudah membusuk adalah...', 'Tanah liat padat kedap air', 'Tanah gembur dengan saluran air (drainase) lancar', 'Tanah becek tergenang air terus-menerus', 'B', 'Tanah gembur berpasir yang porous mencegah air menggenang dan menghindarkan pembusukan pangkal sereh.'),
        ('Tindakan awal yang biasa dilakukan pada batang sereh sebelum dimasukkan ke dalam masakan adalah...', 'Dimemarkan pangkal batangnya', 'Dihaluskan menjadi bubuk kering', 'Dibuang seluruh kulit luar dan dalamnya', 'A', 'Mememarkan pangkal batang sereh bertujuan membuka serat agar minyak atsiri wangi keluar ke masakan.'),
        ('Selain sebagai bumbu dapur, aroma minyak atsiri sereh sering dimanfaatkan masyarakat sebagai...', 'Pewarna alami kain batik', 'Pemberi rasa manis alami', 'Pengusir nyamuk dan serangga alami', 'C', 'Aroma sitronelal dan sitral pada sereh tidak disukai nyamuk sehingga efektif sebagai pengusir serangga alami.'),
        ('Tanaman sereh termasuk ke dalam kelompok flora pekarangan kategori...', 'Tanaman Obat Keluarga (TOGA) dan rempah', 'Pohon buah keras tahunan', 'Tanaman air terapung', 'A', 'Sereh merupakan pilar utama kebun TOGA karena manfaat ganda sebagai bumbu kuliner dan obat herbal.'),
        ('Warna pangkal pelepah batang sereh yang masih segar umumnya adalah...', 'Ungu tua kehitaman', 'Hijau muda keputihan padat', 'Merah terang menyala', 'B', 'Pangkal batang sereh berwarna hijau muda keputihan dengan susunan pelepah yang padat berserat.'),
        ('Penyiraman tanaman sereh di kebun pekarangan sebaiknya dilakukan...', 'Satu bulan sekali', 'Setiap jam tanpa henti', 'Secara teratur 1-2 kali sehari sesuai kelembapan', 'C', 'Sereh membutuhkan air cukup terutama pada masa awal tanam, disiram 1-2 kali sehari tanpa membuat tanah becek.'),
        ('Bagian dari sereh yang biasanya tidak digunakan untuk memasak karena terlalu kering adalah...', 'Ujung helai daun bagian atas', 'Pangkal batang bawah', 'Pelepah muda tengah', 'A', 'Ujung daun sereh bagian atas cenderung kering dan tajam sehingga biasanya dipangkas saat dijadikan bumbu.'),
        ('Sereh dikenal dalam dunia botani internasional dan kuliner mancanegara dengan nama...', 'Cinnamon leaf', 'Lemongrass', 'Sweet basil', 'B', 'Secara internasional, sereh dapur dikenal dengan sebutan lemongrass karena aroma sitrunnya yang khas.'),
        ('Kandungan senyawa aktif utama yang memberikan khasiat menyegarkan pada sereh adalah...', 'Kafein murni', 'Kapsaisin pedas', 'Minyak atsiri sitral', 'C', 'Senyawa sitral merupakan komponen fitokimia dominan pada sereh dapur.')
    ]),
    ('cabai', 'Cabai', [
        ('Senyawa aktif alami yang memberikan rasa pedas khas pada buah cabai adalah...', 'Kapsaisin', 'Kurkumin', 'Sitral', 'A', 'Kapsaisin adalah zat fitokimia pada plasenta cabai yang menstimulasi reseptor panas dan pedas.'),
        ('Kandungan vitamin yang sangat tinggi dan melimpah pada buah cabai segar adalah...', 'Vitamin D', 'Vitamin C', 'Vitamin K', 'B', 'Cabai segar kaya akan vitamin C alami yang bermanfaat meningkatkan daya tahan tubuh.'),
        ('Perubahan warna yang terjadi saat buah cabai mencapai tingkat kematangan sempurna adalah...', 'Merah berubah menjadi biru', 'Kuning berubah menjadi hitam', 'Hijau berubah menjadi merah ranum', 'C', 'Klorofil hijau pada cabai perlahan terurai dan digantikan pigmen karotenoid merah saat matang.'),
        ('Bagian tanaman cabai yang digunakan untuk pembibitan generatif adalah...', 'Biji yang ada di dalam buah', 'Ujung akar tunggang', 'Kulit batang berkayu', 'A', 'Benih cabai diperoleh dari biji buah matang yang dikeringanginkan sebelum disemai.'),
        ('Media tanam yang ideal untuk budidaya cabai di dalam polybag pekarangan adalah...', 'Pasir murni tanpa nutrisi', 'Campuran tanah gembur dan kompos/pupuk kandang', 'Lumpur basah tanpa lubang drainase', 'B', 'Campuran tanah subur dan kompos (1:1) memberikan aerasi yang baik bagi perakaran cabai.'),
        ('Bunga tanaman cabai sebelum menjadi buah umumnya memiliki mahkota berwarna...', 'Hitam pekat', 'Merah darah', 'Putih bersih berbentuk bintang', 'C', 'Bunga cabai berbentuk bintang kecil dengan mahkota berwarna putih atau putih kehijauan.'),
        ('Bentuk fisik buah cabai yang paling umum dijumpai di pekarangan adalah...', 'Bulat lonjong lancip meruncing', 'Bulat gepeng menyerupai labu', 'Kotak kubus beruas', 'A', 'Cabai memiliki buah buni silindris memanjang dengan ujung yang lancip meruncing.'),
        ('Gejala yang terjadi pada tanaman cabai jika disiram berlebihan hingga media tergenang adalah...', 'Akar menjadi sangat kuat', 'Daun menguning dan akar membusuk', 'Buah langsung berlipat ganda', 'B', 'Tanaman cabai tidak tahan genangan air karena menyebabkan busuk akar akibat jamur tanah.'),
        ('Pemanfaatan utama buah cabai dalam tradisi kuliner nusantara adalah...', 'Pewarna alami nasi kuning', 'Bahan pengganti pemanis teh', 'Bahan utama olahan aneka sambal', 'C', 'Cabai merupakan komoditas bumbu pokok masyarakat Indonesia sebagai bahan utama sambal.'),
        ('Batang tanaman cabai memiliki struktur berupa...', 'Perdu semak berkayu semi-lunak', 'Rimpang menjalar di dalam tanah', 'Batang basah tanpa kayu', 'A', 'Cabai bertumbuh sebagai perdu semak rendah dengan batang yang berangsur mengeras berkayu.'),
        ('Waktu yang dibutuhkan untuk persemaian benih biji cabai hingga siap pindah tanam adalah...', 'Satu tahun penuh', 'Sekitar 2 sampai 3 minggu', 'Satu hari setelah disemai', 'B', 'Bibit cabai biasanya memiliki 4 helai daun sejati pada usia 2-3 minggu dan siap dipindah ke polybag.'),
        ('Kebutuhan cahaya matahari untuk tanaman cabai agar rajin berbunga dan berbuah adalah...', 'Tempat gelap tanpa jendela', 'Di bawah lemari pakaian', 'Tempat terbuka mendapat sinar matahari penuh', 'C', 'Cabai memerlukan sinar matahari minimal 6-8 jam sehari untuk fotosintesis dan pembentukan buah.'),
        ('Bagian dari buah cabai yang memiliki tingkat rasa pedas paling tinggi adalah...', 'Plasenta putih tempat menempelnya biji', 'Tangkai hijau buah', 'Kulit luar buah bagian pangkal', 'A', 'Kelenjar penghasil kapsaisin terkonsentrasi pada plasenta atau sekat putih di dalam rongga buah.'),
        ('Bentuk susunan daun pada tanaman cabai adalah...', 'Daun pita memanjang berpelepah', 'Daun tunggal berseling dengan tepi rata', 'Daun jarum berduri keras', 'B', 'Daun cabai merupakan daun tunggal berbentuk bulat telur meruncing dengan permukaan halus.'),
        ('Manfaat rasa pedas cabai dalam porsi yang wajar bagi kesehatan tubuh adalah...', 'Menghambat aliran darah', 'Memicu tubuh cepat mengantuk', 'Menyegarkan metabolisme tubuh dan selera makan', 'C', 'Kapsaisin merangsang pelepasan endorfin serta mempercepat metabolisme tubuh secara alami.')
    ]),
    ('kangkung', 'Kangkung', [
        ('Ciri khas batang tanaman kangkung yang membuatnya renyah dan cepat matang saat dimasak adalah...', 'Batang berongga di bagian tengah', 'Batang keras berlapis kulit kayu', 'Batang berduri runcing rapat', 'A', 'Batang kangkung berongga udara yang memudahkan sirkulasi oksigen dan memberi tekstur renyah.'),
        ('Jangka waktu panen kangkung sejak penanaman benih tergolong sangat singkat yaitu...', 'Enam bulan', 'Sekitar 25 sampai 30 hari', 'Dua tahun', 'B', 'Kangkung adalah sayuran daun berumur pendek yang dapat dipanen dalam waktu kurang dari satu bulan.'),
        ('Sistem budidaya modern di perkotaan (urban farming) yang sangat populer untuk menanam kangkung adalah...', 'Ditanam di puncak pohon tinggi', 'Ditanam di dalam gua tanpa air', 'Hidroponik atau bedengan air pekarangan', 'C', 'Kangkung sangat adaptif terhadap instalasi hidroponik air maupun pot ember wadas.'),
        ('Zat gizi mineral penting yang terkandung tinggi dalam sayuran daun kangkung adalah...', 'Zat besi dan serat pangan', 'Lemak jenuh', 'Kolesterol hewani', 'A', 'Kangkung kaya zat besi nabati yang baik untuk pembentukan sel darah merah serta serat alami.'),
        ('Bunga tanaman kangkung memiliki bentuk menyerupai corong atau terompet dengan warna...', 'Kuning keemasan', 'Putih keunguan atau ungu muda', 'Merah darah menyala', 'B', 'Bunga kangkung berbentuk corong terompet yang mekar anggun dengan warna putih bergradasi ungu.'),
        ('Cara memanen sayuran kangkung di pekarangan dapat dilakukan dengan dua cara yaitu...', 'Dibakar habis pangkalnya', 'Dibiarkan mengering di pohon', 'Dicabut seluruh akarnya atau dipotong pangkal batangnya', 'C', 'Kangkung cabut dipanen dengan akarnya, sedangkan kangkung potong dapat tumbuh kembali untuk panen berikutnya.'),
        ('Kebutuhan utama tanaman kangkung agar tumbuh subur dan daunnya tidak kerdil adalah...', 'Penyiraman air yang melimpah dan tanah lembap', 'Tempat sangat kering berbatu', 'Disimpan di ruangan ber-AC', 'A', 'Sebagai tanaman semi-akuatik, kangkung membutuhkan pasokan air berlimpah dan media yang selalu basah/lembap.'),
        ('Bentuk helai daun kangkung darat umumnya menyerupai...', 'Bulat seperti koin uang', 'Mata panah atau lanset memanjang', 'Segitiga bergerigi tajam', 'B', 'Daun kangkung berbentuk mata panah meruncing berwarna hijau segar dengan urat daun menyirip.'),
        ('Olahan masakan rumah tangga nusantara yang paling terkenal dari sayuran kangkung adalah...', 'Kolak manis', 'Keripik daun kering', 'Tumis kangkung atau plecing kangkung', 'C', 'Tumis kangkung terasi dan plecing kangkung merupakan sajian kuliner sayur daun favorit keluarga.'),
        ('Benih kangkung untuk budidaya di pekarangan diperoleh dari...', 'Biji bulat berwarna cokelat kehitaman', 'Spora jamur mikroskopis', 'Stek bunga yang layu', 'A', 'Biji kangkung berbentuk bulat agak bersudut yang langsung disemai pada media tanah basah.'),
        ('Keunggulan sayuran kangkung dalam program ketahanan pangan keluarga adalah...', 'Hanya bisa dipanen sekali seumur hidup', 'Sangat cepat dipanen dan mudah perawatannya', 'Memerlukan pupuk kimia berdosis tinggi', 'B', 'Pertumbuhan kangkung yang sangat cepat menjadikannya komoditas andalan urban farming perkotaan.'),
        ('Manfaat konsumsi serat pada daun kangkung bagi sistem pencernaan adalah...', 'Membuat perut begah terus-menerus', 'Menghentikan penyerapan air tubuh', 'Membantu melancarkan buang air besar secara alami', 'C', 'Serat alami kangkung menyerap air dan melunakkan kotoran sehingga saluran cerna bekerja lancar.'),
        ('Tekstur batang kangkung saat diolah menjadi masakan yang disukai masyarakat adalah...', 'Renyah basah (crunchy)', 'Keras berkayu', 'Pahit pekat berserat alot', 'A', 'Rongga udara pada batang memberikan sensasi renyah segar saat kangkung dimasak cepat.'),
        ('Tanaman kangkung tergolong ke dalam famili tumbuhan...', 'Keluarga kaktus-kaktusan', 'Convolvulaceae (keluarga ubi jalar)', 'Keluarga kelapa sawit', 'B', 'Kangkung berada dalam genus Ipomoea satu famili dengan ubi jalar yang memiliki bunga terompet serupa.'),
        ('Iklim lingkungan yang paling mendukung budidaya tanaman kangkung di Indonesia adalah...', 'Daerah kutub bersalju', 'Gurun pasir tandus', 'Iklim tropis hangat dengan curah hujan cukup', 'C', 'Kangkung tumbuh optimal pada dataran rendah tropis bersuhu hangat dan berlimpah cahaya matahari.')
    ]),
    ('tomat', 'Tomat', [
        ('Zat antioksidan alami berwarna merah yang terkandung melimpah pada buah tomat adalah...', 'Likopen', 'Klorofil', 'Kapsaisin', 'A', 'Likopen adalah pigmen karotenoid merah kuat yang berfungsi menangkal radikal bebas.'),
        ('Alat bantu dari bambu yang dipancangkan di dekat pohon tomat untuk menopang buah disebut...', 'Tali jemuran', 'Tiang ajir penopang', 'Kawat berduri', 'B', 'Tiang ajir bambu menahan batang tomat agar tidak roboh saat buah tomat mulai membesar dan berbobot.'),
        ('Jenis buah pada tanaman tomat menurut klasifikasi botani adalah...', 'Buah polong berbiji dua', 'Buah batu berkulit keras', 'Buah buni berdaging lunak berair', 'C', 'Tomat merupakan buah buni (berry) yang memiliki dinding buah berair dengan banyak biji kecil.'),
        ('Tindakan pemeliharaan membuang tunas kecil di ketiak daun tomat bertujuan untuk...', 'Memfokuskan nutrisi tanaman pada pembesaran buah', 'Membuat tanaman cepat layu', 'Menghilangkan semua daun tomat', 'A', 'Pemangkasan tunas air (pruning) mengarahkan translokasi nutrisi tanaman langsung ke tangkai buah.'),
        ('Warna bunga tanaman tomat sebelum rontok dan membentuk bakal buah adalah...', 'Merah jambu', 'Kuning cerah', 'Biru keunguan', 'B', 'Bunga tomat mekar berbentuk bintang dengan warna mahkota kuning cerah yang menarik serangga penyerbuk.'),
        ('Batang tanaman tomat memiliki ciri fisik yang khas saat disentuh yaitu...', 'Licin seperti kaca', 'Berduri tajam melengkung', 'Berbulu kelenjar halus dan beraroma khas', 'C', 'Batang dan tangkai daun tomat diselimuti trikoma (bulu kelenjar) yang mengeluarkan aroma aromatik saat tersentuh.'),
        ('Waktu penyiraman yang paling tepat untuk tanaman tomat di pekarangan adalah...', 'Pagi hari pada permukaan tanah/media tanam', 'Tengah hari bolong saat terik matahari', 'Malam hari hingga daun tergenang basah', 'A', 'Menyiram media di pagi hari mencegah kelembapan berlebih pada daun yang bisa memicu penyakit jamur.'),
        ('Tomat banyak dimanfaatkan dalam kehidupan sehari-hari sebagai bahan...', 'Pengganti minyak goreng', 'Pelengkap sayur, jus buah, sup, dan bumbu masakan', 'Bahan pembuat arang bakar', 'B', 'Tomat serbaguna digunakan sebagai buah segar, minuman jus, sup bergizi, dan campuran sambal nusantara.'),
        ('Perubahan warna buah tomat seiring bertambahnya kematangan adalah...', 'Ungu menjadi hijau tua', 'Kuning menjadi biru laut', 'Hijau menjadi oranye hingga merah ranum', 'C', 'Pembentukan likopen saat proses pematangan mengubah warna kulit buah tomat dari hijau menjadi merah segar.'),
        ('Perbanyakan tanaman tomat di kebun urban farming umumnya dilakukan secara...', 'Generatif melalui persemaian biji benih', 'Menanam potongan ranting kering', 'Mencangkok akar bawah tanah', 'A', 'Biji tomat disemai terlebih dahulu selama 2-3 pekan sebelum dipindahkan ke polybag atau bedengan kebun.'),
        ('Kebutuhan sinar matahari harian agar tanaman tomat berbuah lebat adalah...', 'Tanpa cahaya sama sekali', 'Sekitar 6 sampai 8 jam per hari', 'Cukup satu menit setiap pagi', 'B', 'Cahaya matahari penuh selama 6-8 jam per hari sangat penting untuk fotosintesis dan pembentukan gula buah.'),
        ('Manfaat rutin mengonsumsi buah tomat bagi kesehatan tubuh adalah...', 'Membantu menjaga kesehatan mata dan daya tahan sel tubuh', 'Membuat tulang menjadi rapuh', 'Mengurangi jumlah cairan tubuh secara drastis', 'C', 'Kombinasi likopen, vitamin C, dan vitamin A pada tomat mendukung kesehatan sel mata dan imunitas.'),
        ('Biji tomat di dalam rongga buah diselubungi oleh lapisan bertekstur...', 'Gel lendir bening yang licin', 'Serbuk kering seperti tepung', 'Kulit kayu keras berserabut', 'A', 'Lapisan gel musilago di sekitar biji menjaga kelembapan benih dan melindungi embrio di dalamnya.'),
        ('Tanaman tomat tergolong dalam keluarga (famili) tumbuhan yang sama dengan...', 'Keluarga padi-padian', 'Solanaceae (keluarga terung dan cabai)', 'Keluarga pohon cemara', 'B', 'Tomat tergolong Solanaceae bersama dengan tanaman terong dan cabai.'),
        ('Ciri daun tanaman tomat yang mudah dikenali adalah...', 'Daun kaku berbentuk jarum', 'Daun tunggal bundar mengilap', 'Daun majemuk menyirip berseling dengan tepi berlekuk', 'C', 'Daun tomat merupakan daun majemuk menyirip berlekuk tidak beraturan dengan aroma khas aromatik.')
    ]),
    ('terong', 'Terong', [
        ('Warna kulit buah terong yang paling populer dibudidayakan di kebun warga adalah...', 'Ungu gelap mengilap', 'Kuning pucat keemasan', 'Putih bertotol hitam', 'A', 'Terong ungu memiliki kulit buah mulus mengilap berwarna ungu tua dengan daging empuk.'),
        ('Senyawa antioksidan antosianin yang memberi warna ungu pada kulit buah terong disebut...', 'Klorofil', 'Nasunin', 'Sitronelal', 'B', 'Nasunin adalah antioksidan jenis antosianin kuat yang melindungi membran sel otak dan tubuh.'),
        ('Bunga tanaman terong saat mekar memiliki mahkota berwarna...', 'Merah menyala', 'Kuning terang', 'Ungu kebiruan atau putih keunguan', 'C', 'Bunga terong memiliki mahkota ungu kebiruan dengan kepala sari kuning mencolok di tengahnya.'),
        ('Tekstur daging buah terong yang sudah dimasak umumnya terasa...', 'Empuk dan lembut berserat halus', 'Keras seperti ubi kayu mentah', 'Renyah kering seperti kerupuk', 'A', 'Daging terong kaya serat berpori yang menjadi sangat lembut dan empuk saat dimasak matang.'),
        ('Masa panen tanaman terong sejak awal tanam berkisar antara...', 'Sepuluh tahun', 'Sekitar 60 sampai 80 hari', 'Satu minggu', 'B', 'Terong mulai menghasilkan buah siap panen pada umur 2-2.5 bulan setelah tanam.'),
        ('Olahan masakan nusantara yang sangat digemari dari buah terong adalah...', 'Jus manis dingin bersoda', 'Bubur manis santan kental', 'Terong balado dan sayur lodeh', 'C', 'Terong balado bercita rasa gurih pedas dan sayur lodeh santan adalah sajian sayur terong favorit.'),
        ('Ciri fisik batang tanaman terong di pekarangan adalah...', 'Perdu semak rendah dengan daun lebar berbulu halus', 'Tanaman merambat melilit pohon kelapa', 'Batang basah tanpa ranting', 'A', 'Batang terong berbentuk perdu tegak bercabang dengan daun berukuran lebar diselimuti bulu halus.'),
        ('Perbanyakan tanaman terong paling praktis dilakukan melalui...', 'Pencangkokan akar bawah', 'Persemaian biji benih buah matang', 'Pemisahan umbi batang', 'B', 'Benih terong berasal dari biji yang disemai hingga memiliki beberapa helai daun sebelum dipindah.'),
        ('Wadah tanam sederhana yang sangat cocok untuk menanam terong di pekarangan sempit adalah...', 'Kotak pensil kecil', 'Ember cat tanpa lubang air', 'Polybag berukuran 40 cm atau pot tanah', 'C', 'Polybag sedang berdiameter 35-40 cm mampu menampung media tanam yang cukup untuk perakaran terong.'),
        ('Kandungan kalori pada buah terong menjadikannya cocok untuk menu sehat karena...', 'Rendah kalori dan kaya serat pangan nabati', 'Sangat tinggi lemak jahat', 'Mengandung kadar garam buatan tinggi', 'A', 'Kandungan serat tinggi dan kalori rendah membuat terong sangat baik untuk menjaga berat badan dan kolesterol.'),
        ('Kondisi pencahayaan matahari yang dibutuhkan tanaman terong adalah...', 'Tempat gelap tanpa celah', 'Mendapat sinar matahari penuh sepanjang hari', 'Diletakkan di dalam kamar mandi tertutup', 'B', 'Terong memerlukan sinar matahari langsung minimal 6 jam sehari agar rajin berbunga dan berbuah lebat.'),
        ('Bagian dari bunga yang tetap menempel kokoh pada pangkal buah terong hingga dipanen adalah...', 'Kelopak bunga hijau berduri halus', 'Semua benang sari', 'Akar serabut', 'C', 'Kelopak bunga (calyx) berwarna hijau tetap membungkus pangkal buah terong hingga matang.'),
        ('Cara memanen buah terong yang benar agar tidak merusak cabang tanaman adalah...', 'Memotong tangkai buah menggunakan gunting pangkas atau pisau tajam', 'Menarik buah sekuat tenaga sampai ranting patah', 'Mengguncang pohon hingga buah jatuh sendiri', 'A', 'Memotong tangkai dengan gunting bersih mencegah luka robek pada cabang tanaman terong.'),
        ('Tanaman terong merupakan kerabat dekat dalam famili Solanaceae bersama dengan...', 'Padi dan jagung', 'Tomat dan cabai', 'Kelapa dan pisang', 'B', 'Terong, tomat, dan cabai merupakan tiga komoditas pokok dari keluarga botani Solanaceae.'),
        ('Manfaat serat pangan yang tinggi pada daging buah terong bagi tubuh adalah...', 'Menghambat kerja lambung', 'Mempercepat timbulnya rasa haus', 'Memberikan rasa kenyang lebih lama dan menyehatkan pencernaan', 'C', 'Serat larut pada terong memperlambat pengosongan lambung sehingga membantu mengontrol nafsu makan.')
    ]),
    ('jahe', 'Jahe', [
        ('Bagian utama tanaman jahe yang dimanfaatkan sebagai rempah dan obat herbal adalah...', 'Rimpang yang tumbuh bercabang di dalam tanah', 'Biji hitam di pucuk dahan', 'Bunga kuning di atas pohon', 'A', 'Rimpang jahe di bawah permukaan tanah menyimpan cadangan makanan kaya minyak atsiri dan gingerol.'),
        ('Senyawa fitokimia aktif yang memberikan sensasi pedas hangat alami pada jahe adalah...', 'Kafein', 'Gingerol dan shogaol', 'Kurkumin', 'B', 'Gingerol merupakan senyawa bioaktif pedas hangat yang berkhasiat melancarkan peredaran darah.'),
        ('Minuman tradisional nusantara yang populer disajikan hangat dari rimpang jahe adalah...', 'Es teh manis dingin', 'Jus melon bersoda', 'Wedang jahe atau sekoteng', 'C', 'Wedang jahe hangat sangat digemari masyarakat untuk menghangatkan badan dan menyegarkan stamina.'),
        ('Cara perbanyakan tanaman jahe di kebun TOGA dilakukan secara vegetatif menggunakan...', 'Potongan rimpang tua yang memiliki mata tunas', 'Biji bunga yang gugur', 'Stek pucuk daun tanpa rimpang', 'A', 'Bibit jahe berasal dari rimpang tua berbobot 20-30 gram yang telah memunculkan mata tunas sehat.'),
        ('Waktu yang dibutuhkan untuk memanen rimpang jahe tua yang berkualitas optimal adalah...', 'Dua minggu setelah tanam', 'Sekitar 8 sampai 10 bulan', 'Sepuluh tahun penuh', 'B', 'Rimpang jahe membutuhkan waktu 8-10 bulan untuk membentuk serat padat dan aroma minyak atsiri yang kuat.'),
        ('Khasiat tradisional rimpang jahe yang sangat dikenal untuk meredakan gangguan tubuh adalah...', 'Memicu sakit gigi', 'Menurunkan kesadaran', 'Meredakan mual, kembung, dan gejala masuk angin', 'C', 'Kandungan aromatik gingerol membantu merelaksasi otot saluran cerna dan meredakan rasa mual.'),
        ('Media tanam yang ideal untuk budidaya jahe di dalam polybag atau karung adalah...', 'Campuran tanah gembur, sekam bakar, dan pupuk kandang', 'Lumpur becek kedap udara', 'Batu kali padat tanpa tanah', 'A', 'Media porous berpasir gembur memungkinkan rimpang jahe bertunas dan berkembang leluasa tanpa busuk.'),
        ('Struktur batang tanaman jahe yang tampak di atas tanah sebenarnya merupakan...', 'Batang semu yang tersusun dari pelepah daun yang saling memeluk', 'Batang sejati berkambium kayu keras', 'Akar udara yang tumbuh ke atas', 'B', 'Batang jahe di atas tanah adalah batang semu (pseudostem) dari helaian pelepah daun tegak.'),
        ('Warna bagian dalam daging rimpang jahe gajah atau jahe emprit umumnya adalah...', 'Biru tua mengilap', 'Merah darah menyala', 'Kuning muda keputihan berserat aromatik', 'C', 'Daging rimpang jahe berwarna kuning pucat dengan serat halus dan aroma pedas aromatik.'),
        ('Di kebun TOGA Kelurahan Bubakan, tanaman jahe menempati posisi penting sebagai...', 'Tanaman obat unggulan penunjang kesehatan keluarga', 'Pohon peneduh jalan raya', 'Tanaman pagar berduri berbahaya', 'A', 'Jahe adalah primadona tanaman TOGA karena khasiat pengobatan herbalnya yang serbaguna.'),
        ('Kondisi naungan pencahayaan yang disukai tanaman jahe pada masa awal pertumbuhan adalah...', 'Sinar matahari penuh yang membakar tanah', 'Semi-teduh dengan intensitas cahaya cukup', 'Ruang bawah tanah tanpa celah udara', 'B', 'Tunas muda jahe menyukai naungan sebagian agar daun tidak layu terbakar panas terik berlebih.'),
        ('Aroma harum yang tercium saat rimpang jahe diiris disebabkan oleh kandungan...', 'Garam kalsium', 'Minyak pelumas mesin', 'Minyak atsiri alami zingeron dan zingiberen', 'C', 'Minyak atsiri pada kelenjar rimpang jahe menguap saat jaringan rimpang dimemarkan atau diiris.'),
        ('Dalam dunia kuliner nusantara, jahe sering ditambahkan ke dalam masakan daging dan ikan untuk...', 'Menghilangkan aroma amis dan memberi rasa hangat', 'Membuat masakan menjadi berwarna hitam pekat', 'Mencegah masakan cepat matang', 'A', 'Aroma segar pedas jahe sangat ampuh menetralisir aroma amis pada olahan protein laut dan daging.'),
        ('Bentuk rimpang jahe di dalam tanah menyerupai susunan...', 'Kelereng bulat sempurna', 'Jari-jemari bercabang gemuk berbuku-buku', 'Tali panjang tipis tanpa ruas', 'B', 'Rimpang jahe berkembang mendatar membentuk cabang-cabang gemuk yang berbuku dan beruas.'),
        ('Manfaat minum air jahe bagi peredaran darah tubuh adalah...', 'Menghambat aliran darah ke jantung', 'Membuat badan menggigil kedinginan', 'Membantu melebarkan pembuluh darah dan memberi rasa nyaman', 'C', 'Efek hangat jahe merangsang sirkulasi darah tepi sehingga tubuh terasa segar dan bugar.')
    ]),
    ('kencur', 'Kencur', [
        ('Ciri pertumbuhan daun tanaman kencur yang paling unik dan mudah dikenali adalah...', 'Daun tumbuh mendatar rapat menempel di atas permukaan tanah', 'Daun melilit pohon tinggi hingga 10 meter', 'Daun berbentuk jarum berduri panjang', 'A', 'Kencur memiliki batang sangat pendek dengan daun melebar roset yang tumbuh merebah menempel tanah.'),
        ('Minuman jamu tradisional khas Jawa yang bahan utamanya menggunakan rimpang kencur adalah...', 'Wedang ronde', 'Jamu beras kencur', 'Teh manis melati', 'B', 'Beras kencur adalah jamu legendaris yang memadukan sari kencur segar dan tepung beras sangrai.'),
        ('Bunga tanaman kencur yang muncul di antara celah pelepah daun memiliki warna...', 'Hitam legam', 'Merah terang berbulu', 'Putih bersih dengan corak ungu di bagian bibirnya', 'C', 'Bunga kencur berukuran mungil mekar tunggal dengan mahkota putih berhias corak ungu halus.'),
        ('Aroma wangi khas dan menyegarkan dari rimpang kencur berasal dari senyawa aktif...', 'Etil p-metoksisinamat (EPMS)', 'Nikotin tembakau', 'Klorofil daun', 'A', 'Senyawa etil p-metoksisinamat memberikan aroma harum spesifik kencur yang menenangkan tenggorokan.'),
        ('Khasiat herbal rimpang kencur yang paling sering dimanfaatkan secara tradisional adalah...', 'Menurunkan daya ingat', 'Melegakan tenggorokan berdahak dan meredakan batuk', 'Memicu rasa gatal di tenggorokan', 'B', 'Kandungan minyak atsiri kencur bersifat ekspektoran alami yang meredakan batuk dan menghangatkan pita suara.'),
        ('Warna bagian dalam daging rimpang kencur saat dibelah adalah...', 'Kuning keemasan menyala', 'Biru keunguan', 'Putih bersih dengan kulit luar cokelat kehitaman', 'C', 'Daging rimpang kencur berwarna putih cerah dengan tekstur renyah beraroma wangi semerbak.'),
        ('Kondisi lingkungan tumbuh yang paling disukai tanaman kencur adalah...', 'Tempat ternaungi sebagian dengan tanah gembur agak lembap', 'Gurun pasir gersang tanpa air', 'Genangan air dalam seperti kolam ikan', 'A', 'Kencur menyukai kelembapan tanah yang sejuk di bawah naungan pohon atau paranet pekarangan.'),
        ('Masakan tradisional nusantara yang menggunakan kencur sebagai bumbu aroma kunci adalah...', 'Gulai kepala ikan santan kuning', 'Bumbu seblak khas Sunda dan sambal pecel', 'Sup jagung manis krim', 'B', 'Kencur adalah bumbu esensial pada olahan seblak dan sambal pecel yang memberi wangi menggugah selera.'),
        ('Struktur batang tanaman kencur tergolong ke dalam jenis...', 'Pohon kayu keras bercabang', 'Batang semu berduri runcing', 'Herba roset rendah dengan batang sejati sangat pendek', 'C', 'Batang kencur sangat pendek tersembunyi di pangkal roset daun tepat di atas permukaan tanah.'),
        ('Perbanyakan kencur di kebun pekarangan dilakukan menggunakan...', 'Potongan rimpang tua yang memiliki mata tunas', 'Stek helaian daun kering', 'Spora udara jamur', 'A', 'Rimpang kencur bertunas ditanam dangkal menghadap ke atas pada media gembur berpasir.'),
        ('Manfaat meminum jamu beras kencur bagi anak-anak dan orang dewasa adalah...', 'Memicu mual berlebih', 'Menambah nafsu makan dan menyegarkan stamina tubuh', 'Mengakibatkan tubuh terasa lemas', 'B', 'Beras kencur berkhasiat menghangatkan lambung, merangsang nafsu makan, dan memulihkan stamina.'),
        ('Bentuk helai daun kencur yang khas adalah...', 'Jorong melebar hampir bundar dengan ujung meruncing pendek', 'Segitiga berlekuk dalam', 'Garis pita sangat tipis panjang', 'C', 'Helai daun kencur melebar elips dengan urat daun sejajar melengkung menyentuh tanah.'),
        ('Kunci utama agar rimpang kencur tidak membusuk di dalam pot adalah...', 'Menggunakan media porous dengan lubang pembuangan air lancar', 'Menyiram pot hingga tergenang air seperti kolam', 'Menutup pot rapat dengan plastik kedap udara', 'A', 'Drainase lancar mencegah rimpang kencur terendam air berlebih yang memicu jamur busuk rimpang.'),
        ('Kencur tergolong ke dalam kelompok tanaman rempah suku...', 'Gramineae (rumput-rumputan)', 'Zingiberaceae (temu-temuan)', 'Cactaceae (kaktus berduri)', 'B', 'Kencur bersaudara dalam suku Zingiberaceae bersama jahe, kunyit, dan temulawak.'),
        ('Bentuk rimpang kencur di dalam tanah umumnya berwujud...', 'Bulat besar sebesar bola tenis', 'Panjang lurus seperti wortel', 'Rimpang pendek berbuku-buku beruas jari kecil bergerombol', 'C', 'Rimpang kencur tumbuh berkelompok dengan ruas-ruas pendek membulat menyerupai jari tangan kecil.')
    ]),
    ('kunyit', 'Kunyit', [
        ('Warna oranye cerah khas pada rimpang kunyit berasal dari senyawa fitokimia alami...', 'Kurkuminoid (kurkumin)', 'Klorofil', 'Kapsaisin', 'A', 'Kurkuminoid adalah pigmen polifenol kuning-oranye yang berkhasiat sebagai antioksidan alami.'),
        ('Jamu tradisional nusantara yang sangat terkenal menggunakan bahan baku utama kunyit adalah...', 'Wedang uwuh', 'Jamu kunyit asam', 'Kopi jahe', 'B', 'Jamu kunyit asam memadukan perasan rimpang kunyit dan asam jawa untuk kesegaran dan kesehatan lambung.'),
        ('Pemanfaatan rimpang kunyit dalam tradisi kuliner nusantara yang paling populer adalah...', 'Bahan pengembang roti bolu', 'Pemanis alami sirup buah', 'Pewarna alami kuning pada nasi kuning dan bumbu gulai', 'C', 'Kunyit memberi warna kuning cerah alami yang khas dan aroma aromatik pada olahan kuliner nusantara.'),
        ('Ciri daun tanaman kunyit yang membedakannya dari kencur adalah...', 'Daun lanset lebar memanjang dengan tangkai pelepah tegak', 'Daun melingkar bulat menempel tanah', 'Daun berbentuk jarum berduri', 'A', 'Daun kunyit berukuran lebar memanjang dan berdiri tegak dengan pelepah daun yang kokoh.'),
        ('Khasiat kesehatan utama dari senyawa kurkumin pada rimpang kunyit adalah...', 'Memicu iritasi asam lambung', 'Membantu meredakan nyeri perut ringan dan memelihara fungsi saluran cerna', 'Menghambat kerja organ hati', 'B', 'Kurkumin membantu melindungi mukosa lambung dan mendukung kelancaran sekresi empedu pencernaan.'),
        ('Bagian bibit yang digunakan untuk menanam kunyit di kebun pekarangan adalah...', 'Biji bunga kering', 'Helaian daun atas', 'Rimpang induk atau rimpang cabang bertunas sehat', 'C', 'Kunyit diperbanyakan secara vegetatif menggunakan potongan rimpang bertunas berumur tua.'),
        ('Tanda visual pada tanaman kunyit yang menunjukkan bahwa rimpang sudah siap dipanen adalah...', 'Bunga mekar menjadi buah merah', 'Batang berubah menjadi pohon kayu keras', 'Seluruh daun mulai menguning, layu, dan mengering alami', 'A', 'Kunyit siap panen pada umur 8-10 bulan yang ditandai dengan layu dan mengeringnya daun tanaman.'),
        ('Karakteristik fisik rimpang kunyit yang tumbuh di dalam tanah adalah...', 'Rimpang induk bulat dengan cabang silindris beruas jingga terang', 'Umbi tunggal bundar tanpa cabang', 'Akar serabut tanpa daging rimpang', 'B', 'Rimpang kunyit memiliki rimpang induk (empu) bulat yang dikelilingi cabang rimpang silindris.'),
        ('Aktivitas biologis penting yang dimiliki oleh senyawa kurkumin kunyit adalah...', 'Sebagai racun serangga berbahaya', 'Sebagai bahan pemadat adonan kue', 'Sebagai antioksidan dan antiinflamasi alami', 'C', 'Kurkumin terbukti secara ilmiah memiliki khasiat antioksidan yang melindungi sel dari radikal bebas.'),
        ('Kebutuhan tanah yang ideal untuk mendukung perkembangan rimpang kunyit agar besar adalah...', 'Tanah gembur berhumus kaya kompos dengan drainase baik', 'Tanah berbatu keras kedap air', 'Lumpur becek tanpa sirkulasi udara', 'A', 'Tanah gembur memungkinkan rimpang kunyit bernapas dan membesar dengan leluasa di dalam tanah.'),
        ('Selain sebagai jamu, kunyit sering digunakan masyarakat pedesaan secara tradisional sebagai...', 'Bahan pelapis lantai rumah', 'Bahan lulur herbal perawatan kulit tradisional', 'Pengganti bahan bakar minyak', 'B', 'Lulur kunyit tradisional digunakan untuk membersihkan kulit, mencerahkan, dan menghaluskan pori-pori.'),
        ('Suku botani tempat tanaman kunyit bernaung adalah...', 'Cactaceae', 'Solanaceae', 'Zingiberaceae (temu-temuan)', 'C', 'Kunyit (Curcuma longa) merupakan salah satu anggota suku temu-temuan Zingiberaceae.'),
        ('Kedalaman lubang tanam yang dianjurkan saat menanam rimpang kunyit di pekarangan adalah...', 'Sekitar 5 sampai 7 cm dengan mata tunas menghadap ke atas', 'Dua meter di bawah tanah liat', 'Diletakkan di atas genteng rumah', 'A', 'Kedalaman 5-7 cm melindungi rimpang dari terik matahari langsung dan memudahkan tunas menembus tanah.'),
        ('Iklim lingkungan yang paling optimal bagi pertumbuhan kebun kunyit di Indonesia adalah...', 'Daerah pegunungan bersalju dingin', 'Iklim tropis hangat dengan pencahayaan matahari cerah', 'Ruangan dingin tertutup es', 'B', 'Kunyit tumbuh subur di wilayah tropis dataran rendah hingga sedang dengan suhu hangat.'),
        ('Aroma rimpang kunyit saat kulitnya dikupas atau diiris memiliki ciri...', 'Wangi manis seperti permen buah', 'Tidak berbau sama sekali', 'Aroma tanah aromatik yang segar dan khas', 'C', 'Rimpang kunyit segar mengeluarkan aroma aromatik tanah herbal khas minyak atsiri kurkuminoid.')
    ]),
    ('lidah_buaya', 'Lidah Buaya', [
        ('Karakteristik utama daun tanaman lidah buaya yang membuatnya tergolong sukulen adalah...', 'Daun tebal berdaging yang menyimpan banyak cadangan gel berair', 'Daun tipis kering mudah rontok', 'Daun berkayu keras tanpa cairan', 'A', 'Lidah buaya adalah sukulen yang menyimpan air melimpah di dalam gel daging daunnya.'),
        ('Manfaat alami gel lidah buaya yang sangat populer untuk perawatan kulit adalah...', 'Membuat kulit terasa terbakar dan perih', 'Melembapkan kulit alami dan menyejukkan kulit terpapar panas matahari', 'Menghilangkan lapisan pelindung kulit', 'B', 'Gel lidah buaya kaya polisakarida glukomanan yang mengikat air dan mempercepat regenerasi sel kulit.'),
        ('Kemampuan tanaman lidah buaya bertahan hidup di lingkungan pekarangan disebabkan oleh...', 'Kebutuhan pupuk kimia setiap hari', 'Daunnya yang bisa terbang tertiup angin', 'Daya toleransi yang tinggi terhadap kekeringan (hemat air)', 'C', 'Struktur daun sukulen yang dilapisi kutikula tebal menahan penguapan air di musim panas.'),
        ('Bentuk tepi daun tanaman lidah buaya memiliki ciri fisik berupa...', 'Gerigi duri tumpul lunak di sepanjang tepian daun', 'Duri besi panjang yang sangat beracun', 'Renda kain halus lembut', 'A', 'Tepi daun lidah buaya dilengkapi duri-duri lunak tumpul yang berfungsi melindungi cadangan air daun.'),
        ('Olahan minuman segar populer dari daging gel lidah buaya yang dipotong dadu adalah...', 'Kopi hitam panas pekat', 'Minuman nata de aloe atau es lidah buaya segar', 'Minyak sayur goreng', 'B', 'Daging gel bening lidah buaya diolah menjadi minuman segar penyejuk tenggorokan dan lambung.'),
        ('Cara perbanyakan tanaman lidah buaya yang paling mudah dan cepat berhasil adalah...', 'Memisahkan anakan tunas roset kecil dari samping tanaman induk', 'Menanam potongan duri daun kering', 'Menyemai spora lumut', 'C', 'Anakan tunas roset yang tumbuh di pangkal induk dipisahkan saat sudah memiliki perakaran mandiri.'),
        ('Media tanam yang paling baik untuk menanam lidah buaya di dalam pot adalah...', 'Campuran tanah humus, pasir malang, dan kompos berpori lancar', 'Tanah liat becek tanpa lubang pembuangan', 'Batu bata utuh tanpa tanah', 'A', 'Media porous berpasir malang mencegah pembusukan akar akibat kelebihan air siraman.'),
        ('Kebutuhan pencahayaan matahari untuk tanaman lidah buaya di pekarangan adalah...', 'Ruang gelap tanpa jendela', 'Mendapat sinar matahari cerah yang cukup', 'Di dalam lemari pendingin tertutup', 'B', 'Lidah buaya menyukai sinar matahari pagi hingga siang agar daunnya tetap hijau segar dan kokoh.'),
        ('Manfaat tradisional gel lidah buaya bagi kesehatan rambut adalah...', 'Membuat rambut menjadi rontok dan kering', 'Menghilangkan seluruh warna rambut', 'Menjaga kelembapan kulit kepala dan merawat kesuburan rambut', 'C', 'Kandungan enzim dan vitamin pada gel lidah buaya menutrisi akar rambut dan melembapkan helai rambut.'),
        ('Susunan daun tanaman lidah buaya tumbuh membentuk formasi...', 'Roset melingkar tanpa batang sejati yang tinggi', 'Pohon pinus mengerucut', 'Semak belukar berduri kusut', 'A', 'Daun lidah buaya tumbuh tersusun rapi melingkar dari pangkal tengah membentuk formasi roset tajuk.'),
        ('Aturan penyiraman tanaman lidah buaya di pekarangan yang benar adalah...', 'Disiram hemat 2-3 hari sekali saat media mulai mengering', 'Direndam di dalam bak air setiap saat', 'Disiram air panas mendidih setiap pagi', 'B', 'Penyiraman hemat mencegah media terlalu basah yang dapat menyebabkan pangkal daun membusuk.'),
        ('Cairan getah berwarna kekuningan di bawah kulit daun lidah buaya yang berbau khas disebut...', 'Minyak kelapa', 'Susu kedelai', 'Getah aloin', 'C', 'Getah aloin berwarna kekuningan berada di antara kulit dan gel bening, biasanya dibilas saat diolah.'),
        ('Dalam penataan pekarangan rumah, lidah buaya memiliki fungsi ganda yaitu sebagai...', 'Tanaman hias sukulen yang asri sekaligus tanaman obat keluarga (TOGA)', 'Pagar pelindung berduri tajam mematikan', 'Kayu bakar kompor tungku', 'A', 'Lidah buaya mempercantik teras rumah sekaligus siap dipetik gelnya untuk pertolongan luka ringan/kulit.'),
        ('Tekstur bagian dalam daun lidah buaya saat dikupas kulit luarnya adalah...', 'Gel bening transparan kenyal berair', 'Serbuk kering seperti tepung terigu', 'Daging berkayu keras dan alot', 'B', 'Gel bagian dalam lidah buaya berwarna bening transparan dengan kandungan air mencapai lebih dari 98%.'),
        ('Pot wadah tanam lidah buaya wajib memiliki lubang drainase di bagian dasarnya agar...', 'Semut bisa bersarang di dalam pot', 'Tanah cepat habis terbawa air', 'Kelebihan air siraman dapat keluar lancar dan akar tidak busuk', 'C', 'Lubang drainase sangat krusial agar air tidak menggenang di dasar pot yang memicu busuk perakaran.')
    ])
]

all_questions = []
for plant_id, plant_name, q_list in plants_data:
    assert len(q_list) == 15, f'Plant {plant_id} has {len(q_list)} questions, expected 15!'
    for idx, q_tuple in enumerate(q_list, 1):
        q_id = f'q_{plant_id}_{idx:03d}'
        question_text, optA, optB, optC, correct, expl = q_tuple
        assert optA != optB and optA != optC and optB != optC, f'Duplicate options in {q_id}'
        assert correct in ['A', 'B', 'C'], f'Invalid correct answer in {q_id}: {correct}'
        all_questions.append({
            'questionId': q_id,
            'plantId': plant_id,
            'question': question_text,
            'optionA': optA,
            'optionB': optB,
            'optionC': optC,
            'correctAnswer': correct,
            'explanation': expl,
            'order': idx,
            'isActive': True,
            'createdAt': 1727670000000,
            'updatedAt': 1727670000000
        })

print(f'Total questions generated: {len(all_questions)}')
assert len(all_questions) == 135, f'Expected 135 questions, got {len(all_questions)}'

out_path = os.path.join('docs', 'data', 'DEFAULT_QUIZ_QUESTIONS.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(all_questions, f, indent=2, ensure_ascii=False)
print(f'Written successfully to {out_path}')

# Generate DEFAULT_PLANT_VOICES.json
plant_voices = []
for plant_id, plant_name, _ in plants_data:
    plant_voices.append({
        'plantId': plant_id,
        'language': 'zh-CN',
        'audioUrl': None,
        'isActive': True,
        'createdAt': 1727670000000,
        'updatedAt': 1727670000000
    })

voice_path = os.path.join('docs', 'data', 'DEFAULT_PLANT_VOICES.json')
with open(voice_path, 'w', encoding='utf-8') as f:
    json.dump(plant_voices, f, indent=2, ensure_ascii=False)
print(f'Written successfully to {voice_path}')
